// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-gzF5Ud0cbAhk0X1imILAMqvWDR0i2gI',
    appId: '1:167441524708:web:82e318cf13b494a2bf89f1',
    messagingSenderId: '167441524708',
    projectId: 'kinclongin',
    authDomain: 'kinclongin.firebaseapp.com',
    storageBucket: 'kinclongin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrgo8zL9k2bMIEYEXjMJ2MmO7m6U-0u7A',
    appId: '1:167441524708:android:4ec139435c6c9aafbf89f1',
    messagingSenderId: '167441524708',
    projectId: 'kinclongin',
    storageBucket: 'kinclongin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBfYSwVcb7uqp7ThTsnIKLybXiD79a2zM',
    appId: '1:167441524708:ios:442ffc811475d919bf89f1',
    messagingSenderId: '167441524708',
    projectId: 'kinclongin',
    storageBucket: 'kinclongin.firebasestorage.app',
    iosBundleId: 'com.example.kinclongIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBfYSwVcb7uqp7ThTsnIKLybXiD79a2zM',
    appId: '1:167441524708:ios:442ffc811475d919bf89f1',
    messagingSenderId: '167441524708',
    projectId: 'kinclongin',
    storageBucket: 'kinclongin.firebasestorage.app',
    iosBundleId: 'com.example.kinclongIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-gzF5Ud0cbAhk0X1imILAMqvWDR0i2gI',
    appId: '1:167441524708:web:1a5b1b97c02b0f89bf89f1',
    messagingSenderId: '167441524708',
    projectId: 'kinclongin',
    authDomain: 'kinclongin.firebaseapp.com',
    storageBucket: 'kinclongin.firebasestorage.app',
  );
}
